### ISSUE TITLE
qmlweb_parse is not defined

### ISSUE THREAD

**Issue by mrjoshuak** [qmlweb/gulp-qmlweb#6]
Not sure how one is supposed to setup qmlweb with or without gulp, but following the Readmes on both projects leads me to this error: 

``` bash
> gulp
...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: /.../qmlweb_test/src/qml/main.qml: ReferenceError: qmlweb_parse is not defined
  at Stream.modifyFile (/.../qmlweb_test/node_modules/gulp-qmlweb/index.js:26:33)
  at Stream.stream.write (/.../qmlweb_test/node_modules/through/index.js:26:11)
```

I have a gulpfile.js with the task, and requires from the example, and these devDependencies in package.json:

``` json
    "gulp-qmlweb": "0.0.4",
    "qmlweb": "^0.1.0",
    "qmlweb-parser": "^0.2.0",
```

I tried with and without the explicit "qmlweb-parser" dependency.

**Comment by mrjoshuak** [comment]
The gulp task for the above error looks like this:

``` javascript
var qml = require('gulp-qmlweb');
var concat = require('gulp-concat');

//...

gulp.task('qml', function() {
  return gulp.src(['src/qml/**/*.qml', 'src/qml/**/*.js', 'src/qml/**/qmldir'])
    .pipe(qml())
    .pipe(concat('qrc.js'))
    .pipe(gulp.dest('src/js'));
});
```

**Comment by ChALkeR** [comment]
Argh, it looks like I made a mistake in the last commit (ef1fd30edfd7d157c3dea76d934e5ad82a5ce582).

Could you try replacing `data = parser.qmlweb_parse(str, qmlweb_parse.QMLDocument);` with `data = parser.qmlweb_parse(str, parser.qmlweb_parse.QMLDocument);` in `./node_modules/gulp-qmlweb/index.js` and check if that works?

**Comment by mrjoshuak** [comment]
Yes that fixes this error.

**Comment by ChALkeR** [comment]
v0.0.5 is out that fixes this bug.

**Comment by mrjoshuak** [comment]
v0.0.5 seems to have introduced new issues in index.js

**Comment by ChALkeR** [comment]
@JoshuaKolden Argh. We definitely need tests here.

**Comment by ChALkeR** [comment]
@JoshuaKolden Is it good now?

**Comment by mrjoshuak** [comment]
`"gulp-qmlweb": "0.0.6"`

``` bash
> gulp
#...
TypeError: Cannot read property 'pathFilter' of undefined
  at module.exports (/.../qmlweb_test/node_modules/gulp-qmlweb/index.js:6:23)
```

**Comment by ChALkeR** [comment]
@JoshuaKolden Argh! I couldn't test that atm, sorry.

Try passing an empty options object for now, i.e. `.pipe(qml({}))` — that should work. I will test things and push an update shortly.

**Comment by mrjoshuak** [comment]
Ok, that works as an interim solution. Though I'm still trying to figure out how to use all this properly, and I'm sure I have the wrong workflow.  I can't seem to get precompiled qrc.js to supersede a client request for the qml file. And I'm not sure if it's using the precompiled qml or dynamically rendering the qml that is requested by the web page.

**Comment by ChALkeR** [comment]
@JoshuaKolden Options object should be not necessary now, in v0.0.7.

**Comment by mrjoshuak** [comment]
Thanks.  Any idea why I'd be getting `No constructor found for TextField`?  Other QtQuck core options seem to work fine.

**Comment by ChALkeR** [comment]
@JoshuaKolden No. Could you file a separate issue for that in https://github.com/qmlweb/qmlweb/, with a sample code to reproduce the issue?

**Comment by mrjoshuak** [comment]
Ok.  Filed at: [No constructor found #277](https://github.com/qmlweb/qmlweb/issues/277)
